version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    
  app:
    build: .
    container_name: app
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis