basePath: /api
definitions:
  handlers.InteractionRequest:
    properties:
      interaction_type:
        type: string
      user_id:
        type: string
      value:
        type: number
      video_id:
        type: string
    required:
    - interaction_type
    - video_id
    type: object
  handlers.VideoScore:
    properties:
      score:
        type: number
      video_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a Microservice Ranking Video to rank videos based on user interactions.
  title: Video Rank API
  version: "1.0"
paths:
  /interactions:
    post:
      consumes:
      - application/json
      description: Update the rank of a video based on user interaction
      parameters:
      - description: Interaction details
        in: body
        name: interaction
        required: true
        schema:
          $ref: '#/definitions/handlers.InteractionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Handle interaction
      tags:
      - interactions
  /rankings:
    get:
      consumes:
      - application/json
      description: Get the top-n global rankings or user rankings
      parameters:
      - description: User ID for personalized ranking
        in: query
        name: user_id
        type: string
      - default: 10
        description: Number of results to return
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.VideoScore'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get rankings
      tags:
      - rankings
schemes:
- http
swagger: "2.0"
